server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://43.142.99.26:3306/cloud_user?useSSL=false
    username: root
    password: 3333
    driver-class-name: com.mysql.jdbc.Driver
#  application:
#    name: userservice #user的服务名称
#  cloud:
#    nacos:
#      server-addr: localhost:8848
#      discovery:
#        cluster-name: SH #集群名称湖北
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#feign:
#  client:
#    config:
#      default: # 这里用default就是全局配置，如果是写服务名称，则是针对某个微服务的配置
#        loggerLevel: FULL #  日志级别


#eureka:
#  client:
#    service-url: #eureka的地址信息
#      defaultZone: http://127.0.0.1:10086/eureka