server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://43.142.99.26:3306/cloud_order?useSSL=false
    username: root
    password: 3333
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        cluster-name: HB #集群名称
        namespace: 9d17056f-b4a6-4135-b9a2-07dbbc1654bb #命名空间 dev
        ephemeral: false #是否是临时实例

  application:
    name: orderserver #的服务名称
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#eureka:
#  client:
#    service-url: #eureka的地址信息
#      defaultZone: http://127.0.0.1:10086/eureka
#userservice:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule # 负载均衡规则
userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule   # nacos负载均衡规则
ribbon:
  eager-load:
    clients:
      - userservice
    enabled: true